import 'package:flutter/material.dart';

final List<Map<String, dynamic>> diseases = [
  {
    'name': 'Northern Corn Leaf Blight',
    'symptoms': 'Long, cigar-shaped lesions on leaves',
    'treatment': 'Apply fungicides, use resistant varieties',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Common Rust',
    'symptoms': 'Small, reddish-brown pustules on leaves',
    'treatment': 'Early fungicide application, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Gray Leaf Spot',
    'symptoms': 'Rectangular lesions between leaf veins',
    'treatment': 'Fungicide treatment, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Southern Corn Leaf Blight',
    'symptoms': 'Small, tan lesions with dark borders',
    'treatment': 'Resistant hybrids, proper field management',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Blight',
    'symptoms': 'Dark spots on leaves and fruit, wilting',
    'treatment': 'Fungicide application, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cucumber Mosaic Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control aphids',
    'severity': 'Medium',
    'color': Colors.yellow,
  },
  {
    'name': 'Powdery Mildew',
    'symptoms': 'White powdery spots on leaves',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Downy Mildew',
    'symptoms': 'Yellow patches on leaves, grayish mold underneath',
    'treatment': 'Fungicide application, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Wilt',
    'symptoms': 'Wilting of leaves, darkening of vascular tissue',
    'treatment': 'Remove infected plants, crop rotation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Wilt',
    'symptoms': 'Yellowing of leaves, wilting, stunted growth',
    'treatment': 'Use resistant varieties, crop rotation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Knot Nematode',
    'symptoms': 'Galls on roots, stunted growth',
    'treatment': 'Crop rotation, nematicides',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Leaf Spot',
    'symptoms': 'Brown or black spots on leaves',
    'treatment': 'Fungicide application, remove infected leaves',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Anthracnose',
    'symptoms': 'Dark, sunken lesions on fruits and leaves',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Sclerotinia Rot',
    'symptoms': 'White, fluffy mold on stems and leaves',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Black Rot',
    'symptoms': 'V-shaped lesions on leaves, blackening of veins',
    'treatment': 'Fungicide application, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cabbage Worm',
    'symptoms': 'Holes in leaves, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    ' severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Spider Mites',
    'symptoms': 'Webbing on leaves, stippling damage',
    'treatment': 'Miticides, increase humidity',
    'severity': 'Medium',
    'color': Colors.yellow,
  },
  {
    'name': 'Blossom End Rot',
    'symptoms': 'Dark, sunken spots on the blossom end of fruits',
    'treatment': 'Calcium supplementation, consistent watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Leaf Spot',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Canker',
    'symptoms': 'Lesions on leaves and fruit, leaf drop',
    'treatment': 'Remove infected parts, fungicide application',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Peach Leaf Curl',
    'symptoms': 'Curling and reddening of leaves',
    'treatment': 'Fungicide application, prune infected branches',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Mosaic Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control aphids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Late Blight',
    'symptoms': 'Dark, water-soaked spots on leaves and stems',
    'treatment': 'Fungicide application, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Early Blight',
    'symptoms': 'Target-like spots on leaves, yellowing',
    'treatment': 'Fungicide application, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Crown Gall',
    'symptoms': 'Tumors on roots and stems',
    'treatment': 'Remove infected plants, avoid injury to roots',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Fire Blight',
    'symptoms': 'Wilting and blackening of blossoms and shoots',
    'treatment': 'Prune infected branches, apply bactericides',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Powdery Mildew on Grapes',
    'symptoms': 'White powdery spots on leaves and fruit',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'White Mold',
    'symptoms': 'White, fluffy growth on stems and leaves',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot',
    'symptoms': 'Soft, mushy spots on fruits and vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Soybean Rust',
    'symptoms': 'Small, reddish-brown pustules on leaves',
    'treatment': 'Fungicide application, resistant varieties',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Aspergillus Rot',
    'symptoms': 'Black mold on fruits and vegetables',
    'treatment': 'Remove infected parts, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    't reatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Pe as',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': ' Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft , mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids,',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': ' High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Pea Leaf Weevil',
    'symptoms': 'Notched leaves, visible weevils',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Onion Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Potato Scab',
    'symptoms': 'Rough, scabby lesions on tubers',
    'treatment': 'Improve soil pH, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Fruit Worm',
    'symptoms': 'Holes in fruit, visible caterpillars',
    'treatment': 'Insecticides, handpicking',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Canker',
    'symptoms': 'Water-soaked spots on leaves and stems',
    'treatment': 'Remove infected plants, avoid overhead watering',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Fusarium Root Rot',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Root Maggot',
    'symptoms': 'Wilting, stunted growth, visible maggots in soil',
    'treatment': 'Insecticides, crop rotation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Spotted Wilt Virus',
    'symptoms': 'Mosaic pattern on leaves, stunted growth',
    'treatment': 'Remove infected plants, control thrips',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Aphid',
    'symptoms': 'Sticky leaves, visible aphids',
    'treatment': 'Insecticides, natural predators',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Blackleg',
    'symptoms': 'Dark lesions on stems, wilting',
    'treatment': 'Remove infected plants, improve drainage',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Crown Rot in Tomatoes',
    'symptoms': 'Wilting, yellowing leaves, darkened crown',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Bacterial Soft Rot in Vegetables',
    'symptoms': 'Soft, mushy spots on vegetables',
    'treatment': 'Remove infected parts, improve drainage',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Cucumber Beetle',
    'symptoms': 'Notched leaves, visible beetles',
    'treatment': 'Insecticides, row covers',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Tomato Yellow Leaf Curl Virus',
    'symptoms': 'Curling and yellowing of leaves',
    'treatment': 'Remove infected plants, control whiteflies',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Root Rot in Peas',
    'symptoms': 'Wilting, yellowing leaves, root decay',
    'treatment': 'Improve drainage, remove infected plants',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Cabbage Downy Mildew',
    'symptoms': 'Yellow patches on leaves, gray mold underneath',
    'treatment': 'Fungicide application, improve air circulation',
    'severity': 'High',
    'color': Colors.red,
  },
  {
    'name': 'Tomato Pith Necrosis',
    'symptoms': 'Dark, sunken lesions on stems',
    'treatment': 'Remove infected plants, improve air circulation',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Bacterial Blight',
    'symptoms': 'Water-soaked spots on leaves, yellowing',
    'treatment': 'Remove infected leaves, avoid overhead watering',
    'severity': 'Medium',
    'color': Colors.orange,
  },
  {
    'name': 'Citrus Greening',
    'symptoms': 'Yellowing of leaves, misshapen fruit',
    'treatment': 'Remove infected trees, control psyllids',
    'severity': 'High',
    'color': Colors.red,
  },
];
